name: Build Python App Cross-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            id: linux
            platform: linux
            pyinstaller_args: "--onefile"
            artifact_name: main-linux_x86_64

          - os: windows-latest
            id: win64
            platform: win64
            pyinstaller_args: "--onefile"
            artifact_name: main-win64.exe

          - os: windows-latest
            id: win32
            platform: win32
            pyinstaller_args: "--onefile --target-arch=32bit"
            artifact_name: main-win32.exe

          - os: macos-13  # Intel runner
            id: mac_intel
            platform: macos_intel
            pyinstaller_args: "--onefile"
            artifact_name: main-mac-intel

          - os: macos-14  # Apple Silicon runner
            id: mac_silicon
            platform: macos_silicon
            pyinstaller_args: "--onefile"
            artifact_name: main-mac-silicon

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        }

    - name: Build executable
      run: |
        pyinstaller ${{ matrix.pyinstaller_args }} main.py

    - name: Rename and move binary
      shell: bash
      run: |
        mkdir -p dist_release
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          mv dist/main.exe dist_release/${{ matrix.artifact_name }}
        else
          mv dist/main dist_release/${{ matrix.artifact_name }}
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist_release/${{ matrix.artifact_name }}
